spring:
  application:
    name: libraryapp

  datasource:
    url: jdbc:postgresql://localhost:5432/librarydb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


google:
  books:
    api-url: https://www.googleapis.com/books/v1

server:
  port: 8080
